{% set name = "openqdc" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openqdc-{{ version }}.tar.gz
  sha256: 694f4376ede84e1ae4246dcb71dc3d4cdefd7639cd598d674afe1f651b49d44c

build:
  entry_points:
    - openqdc = openqdc.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - tqdm
    - pyyaml
    - loguru
    - fsspec <=2023.12.2
    - gcsfs
    - typer
    - prettytable
    - pandas
    - numpy
    - datamol
    - rdkit
    - ase
    - gdown
    - h5py >=3.8.0
    - dscribe
    - zarr
    - python-dotenv
    - s3fs
    - httpx

test:
  imports:
    - openqdc
  commands:
    - pip check
    - openqdc --help
  requires:
    - pip

about:
  home: https://github.com/valence-labs/openQDC
  summary: ML ready Quantum Mechanical datasets
  license: CC-BY-NC-4.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FNTwin
